-- Create the TrustHub database and tables
CREATE DATABASE IF NOT EXISTS trusthub;
USE trusthub;

CREATE TABLE IF NOT EXISTS movies (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  year YEAR,
  genre VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS reviews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  movie_id INT NOT NULL,
  rating INT NOT NULL,
  review TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (movie_id) REFERENCES movies(id)
);

-- ADD A TIMESTAMP FOR REVIEWS
USE trusthub;

ALTER TABLE reviews
  ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- MOVIES INSERT
INSERT INTO movies (title, year, genre) VALUES
('The Shawshank Redemption', 1994, 'Drama'),
('The Godfather', 1972, 'Crime'),
('The Dark Knight', 2008, 'Action'),
('The Godfather Part II', 1974, 'Crime'),
('12 Angry Men', 1957, 'Drama'),
('Schindler\'s List', 1993, 'Biography'),
('The Lord of the Rings: The Return of the King', 2003, 'Fantasy'),
('Pulp Fiction', 1994, 'Crime'),
('The Good, the Bad and the Ugly', 1966, 'Western'),
('Forrest Gump', 1994, 'Drama'),
('Fight Club', 1999, 'Drama'),
('Inception', 2010, 'Sci-Fi'),
('The Lord of the Rings: The Fellowship of the Ring', 2001, 'Fantasy'),
('Star Wars: Episode V - The Empire Strikes Back', 1980, 'Sci-Fi'),
('The Matrix', 1999, 'Sci-Fi'),
('Goodfellas', 1990, 'Crime'),
('One Flew Over the Cuckoo\'s Nest', 1975, 'Drama'),
('Se7en', 1995, 'Crime'),
('The Silence of the Lambs', 1991, 'Thriller'),
('City of God', 2002, 'Crime'),
('Saving Private Ryan', 1998, 'War'),
('Interstellar', 2014, 'Sci-Fi'),
('The Green Mile', 1999, 'Fantasy'),
('Life Is Beautiful', 1997, 'Comedy'),
('Spirited Away', 2001, 'Animation'),
('Léon: The Professional', 1994, 'Action'),
('The Usual Suspects', 1995, 'Mystery'),
('Harakiri', 1962, 'Drama'),
('The Lion King', 1994, 'Animation'),
('Back to the Future', 1985, 'Sci-Fi'),
('Terminator 2: Judgment Day', 1991, 'Action'),
('Whiplash', 2014, 'Drama'),
('Gladiator', 2000, 'Action'),
('The Prestige', 2006, 'Mystery'),
('The Departed', 2006, 'Crime'),
('Parasite', 2019, 'Thriller'),
('The Pianist', 2002, 'Biography'),
('Joker', 2019, 'Crime'),
('Alien', 1979, 'Horror'),
('The Shining', 1980, 'Horror'),
('Avengers: Infinity War', 2018, 'Action'),
('Avengers: Endgame', 2019, 'Action'),
('Django Unchained', 2012, 'Western'),
('The Wolf of Wall Street', 2013, 'Biography'),
('Oldboy', 2003, 'Thriller'),
('WALL·E', 2008, 'Animation'),
('American Beauty', 1999, 'Drama'),
('Coco', 2017, 'Animation'),
('Your Name', 2016, 'Animation'),
('Toy Story', 1995, 'Animation');

--  Fake reviews for (150 rows, 3 per movie) (ai generated)
INSERT INTO reviews (movie_id, rating, review) VALUES
(1, 4, 'The Shawshank Redemption absolutely loved it.'),
(1, 5, 'The Shawshank Redemption stands the test of time.'),
(1, 3, 'The Shawshank Redemption was enjoyable.'),
(2, 5, 'The Godfather left me speechless.'),
(2, 2, 'The Godfather left me wanting more.'),
(2, 4, 'The Godfather is near perfect.'),
(3, 2, 'The Dark Knight wasn''t my cup of tea.'),
(3, 5, 'The Dark Knight exceeded my expectations.'),
(3, 2, 'The Dark Knight didn''t live up to the hype.'),
(4, 4, 'The Godfather Part II exceeded my expectations.'),
(4, 3, 'The Godfather Part II holds up well.'),
(4, 2, 'The Godfather Part II is overrated.'),
(5, 4, '12 Angry Men absolutely loved it.'),
(5, 2, '12 Angry Men has pacing issues.'),
(5, 2, '12 Angry Men has pacing issues.'),
(6, 3, 'Schindler''s List is well made.'),
(6, 5, 'Schindler''s List left me speechless.'),
(6, 2, 'Schindler''s List didn''t age well.'),
(7, 4, 'The Lord of the Rings: The Return of the King absolutely loved it.'),
(7, 5, 'The Lord of the Rings: The Return of the King is a masterpiece.'),
(7, 3, 'The Lord of the Rings: The Return of the King was solid entertainment.'),
(8, 1, 'Pulp Fiction is overrated.'),
(8, 3, 'Pulp Fiction was solid entertainment.'),
(8, 3, 'Pulp Fiction has its charms.'),
(9, 5, 'The Good, the Bad and the Ugly absolutely loved it.'),
(9, 1, 'The Good, the Bad and the Ugly was underwhelming.'),
(9, 4, 'The Good, the Bad and the Ugly absolutely loved it.'),
(10, 4, 'Forrest Gump left me speechless.'),
(10, 5, 'Forrest Gump is a masterpiece.'),
(10, 4, 'Forrest Gump is brilliantly crafted.'),
(11, 5, 'Fight Club is an all-time favorite.'),
(11, 4, 'Fight Club was blown away.'),
(11, 2, 'Fight Club felt overrated.'),
(12, 3, 'Inception provides a good experience.'),
(12, 2, 'Inception felt overrated.'),
(12, 5, 'Inception left me speechless.'),
(13, 4, 'The Lord of the Rings: The Fellowship of the Ring exceeded my expectations.'),
(13, 3, 'The Lord of the Rings: The Fellowship of the Ring was pretty good overall.'),
(13, 2, 'The Lord of the Rings: The Fellowship of the Ring didn''t age well.'),
(14, 5, 'Star Wars: Episode V - The Empire Strikes Back is brilliantly crafted.'),
(14, 5, 'Star Wars: Episode V - The Empire Strikes Back left me speechless.'),
(14, 3, 'Star Wars: Episode V - The Empire Strikes Back had some great moments.'),
(15, 1, 'The Matrix failed to grab me.'),
(15, 2, 'The Matrix felt overrated.'),
(15, 5, 'The Matrix absolutely loved it.'),
(16, 3, 'Goodfellas has its charms.'),
(16, 2, 'Goodfellas was underwhelming.'),
(16, 2, 'Goodfellas didn''t live up to the hype.'),
(17, 4, 'One Flew Over the Cuckoo''s Nest stands the test of time.'),
(17, 3, 'One Flew Over the Cuckoo''s Nest was worth the watch.'),
(17, 5, 'One Flew Over the Cuckoo''s Nest is a masterpiece.'),
(18, 4, 'Se7en is brilliantly crafted.'),
(18, 5, 'Se7en deserves all the praise.'),
(18, 3, 'Se7en had some great moments.'),
(19, 3, 'The Silence of the Lambs didn''t disappoint.'),
(19, 4, 'The Silence of the Lambs is near perfect.'),
(19, 5, 'The Silence of the Lambs left me speechless.'),
(20, 5, 'City of God is an all-time favorite.'),
(20, 3, 'City of God was pretty good overall.'),
(20, 2, 'City of God left me wanting more.'),
(21, 4, 'Saving Private Ryan deserves all the praise.'),
(21, 3, 'Saving Private Ryan was enjoyable.'),
(21, 2, 'Saving Private Ryan fell short for me.'),
(22, 3, 'Interstellar holds up well.'),
(22, 2, 'Interstellar didn''t live up to the hype.'),
(22, 4, 'Interstellar is brilliantly crafted.'),
(23, 4, 'The Green Mile absolutely loved it.'),
(23, 3, 'The Green Mile had some great moments.'),
(23, 5, 'The Green Mile left me speechless.'),
(24, 5, 'Life Is Beautiful exceeded my expectations.'),
(24, 3, 'Life Is Beautiful was enjoyable.'),
(24, 4, 'Life Is Beautiful is brilliantly crafted.'),
(25, 5, 'Spirited Away is a masterpiece.'),
(25, 4, 'Spirited Away was blown away.'),
(25, 3, 'Spirited Away provides a good experience.'),
(26, 4, 'Léon: The Professional is near perfect.'),
(26, 3, 'Léon: The Professional was pretty good overall.'),
(26, 5, 'Léon: The Professional left me speechless.'),
(27, 4, 'The Usual Suspects exceeded my expectations.'),
(27, 3, 'The Usual Suspects was enjoyable.'),
(27, 2, 'The Usual Suspects felt overrated.'),
(28, 3, 'Harakiri was worth the watch.'),
(28, 2, 'Harakiri has pacing issues.'),
(28, 4, 'Harakiri is near perfect.'),
(29, 5, 'The Lion King absolutely loved it.'),
(29, 4, 'The Lion King is brilliantly crafted.'),
(29, 3, 'The Lion King was enjoyable.'),
(30, 5, 'Back to the Future left me speechless.'),
(30, 4, 'Back to the Future deserves all the praise.'),
(30, 3, 'Back to the Future provides a good experience.'),
(31, 2, 'Terminator 2: Judgment Day didn''t live up to the hype.'),
(31, 3, 'Terminator 2: Judgment Day was worth the watch.'),
(31, 5, 'Terminator 2: Judgment Day is a masterpiece.'),
(32, 4, 'Whiplash stands the test of time.'),
(32, 3, 'Whiplash was enjoyable.'),
(32, 5, 'Whiplash exceeded my expectations.'),
(33, 5, 'Gladiator left me speechless.'),
(33, 3, 'Gladiator provides a good experience.'),
(33, 4, 'Gladiator was blown away.'),
(34, 3, 'The Prestige holds up well.'),
(34, 5, 'The Prestige is an all-time favorite.'),
(34, 4, 'The Prestige absolutely loved it.'),
(35, 2, 'The Departed was underwhelming.'),
(35, 4, 'The Departed stands the test of time.'),
(35, 3, 'The Departed had some great moments.'),
(36, 5, 'Parasite left me speechless.'),
(36, 4, 'Parasite is brilliantly crafted.'),
(36, 3, 'Parasite provides a good experience.'),
(37, 5, 'The Pianist exceeded my expectations.'),
(37, 3, 'The Pianist has its charms.'),
(37, 4, 'The Pianist absolutely loved it.'),
(38, 4, 'Joker is near perfect.'),
(38, 3, 'Joker holds up well.'),
(38, 2, 'Joker left me wanting more.'),
(39, 2, 'Alien was underwhelming.'),
(39, 1, 'Alien failed to grab me.'),
(39, 3, 'Alien has its charms.'),
(40, 4, 'The Shining absolutely loved it.'),
(40, 5, 'The Shining left me speechless.'),
(40, 2, 'The Shining didn''t live up to the hype.'),
(41, 3, 'Avengers: Infinity War was solid entertainment.'),
(41, 4, 'Avengers: Infinity War deserves all the praise.'),
(41, 5, 'Avengers: Infinity War exceeded my expectations.'),
(42, 5, 'Avengers: Endgame is a masterpiece.'),
(42, 4, 'Avengers: Endgame absolutely loved it.'),
(42, 3, 'Avengers: Endgame provides a good experience.'),
(43, 5, 'Django Unchained left me speechless.'),
(43, 4, 'Django Unchained is brilliantly crafted.'),
(43, 3, 'Django Unchained was enjoyable.'),
(44, 2, 'The Wolf of Wall Street felt overrated.'),
(44, 2, 'The Wolf of Wall Street was underwhelming.'),
(44, 3, 'The Wolf of Wall Street holds up well.'),
(45, 4, 'Oldboy absolutely loved it.'),
(45, 3, 'Oldboy was worth the watch.'),
(45, 5, 'Oldboy is a masterpiece.'),
(46, 3, 'WALL·E provides a good experience.'),
(46, 4, 'WALL·E is near perfect.'),
(46, 5, 'WALL·E exceeded my expectations.'),
(47, 4, 'American Beauty absolutely loved it.'),
(47, 3, 'American Beauty was enjoyable.'),
(47, 5, 'American Beauty left me speechless.'),
(48, 3, 'Coco didn''t disappoint.'),
(48, 4, 'Coco is a masterpiece.'),
(48, 4, 'Coco was blown away.'),
(49, 5, 'Your Name is near perfect.'),
(49, 3, 'Your Name didn''t disappoint.'),
(49, 5, 'Your Name exceeded my expectations.'),
(50, 3, 'Toy Story was solid entertainment.'),
(50, 2, 'Toy Story has pacing issues.'),
(50, 1, 'Toy Story failed to grab me.');
